In [5]:
mat <- matrix(rnorm(16),4)
mat

[,1]       [,2]        [,3]      [,4]      
[1,]  0.4189386 -0.01458280 -1.247364  1.2718361
[2,] -0.7765370 -0.08046722 -0.123114 -0.2850519
[3,] -1.2971716 -0.90456840 -2.093755  0.7175783
[4,] -0.1499491 -2.10868422  1.640839  1.1473185

In [6]:
eigen(mat)

$values
[1] -3.048922+0.00000i  1.985940+0.00000i  0.227508+0.63411i  0.227508-0.63411i

$vectors
              [,1]           [,2]                  [,3]                  [,4]
[1,]  0.4088791+0i  0.59109334+0i  0.6070528+0.0000000i  0.6070528+0.0000000i
[2,]  0.1174276+0i -0.32478673+0i -0.3450559+0.3366483i -0.3450559-0.3366483i
[3,]  0.8654033+0i  0.01391121+0i -0.3091407+0.0689106i -0.3091407-0.0689106i
[4,] -0.2647748+0i  0.73819288+0i -0.3985195+0.3741080i -0.3985195-0.3741080i

In [7]:
ide.P <- function(X) X %*% solve(t(X) %*% X) %*% t(X)
#ide.M <- function(X) I # I can't identify the mud pdf file exactly


In [9]:
mat2 <- ide.P(mat)
mat2

[,1]         [,2]          [,3]         [,4]         
[1,] 1.000000e+00  3.941292e-15 4.440892e-16 -2.886580e-15
[2,] 5.773160e-15  1.000000e+00 4.440892e-16  3.996803e-15
[3,] 3.996803e-15 -2.275957e-15 1.000000e+00  3.330669e-16
[4,] 3.164136e-15 -1.387779e-16 3.053113e-15  1.000000e+00

In [10]:
mat2 %*% mat2

[,1]         [,2]          [,3]         [,4]         
[1,] 1.000000e+00  7.882583e-15 8.881784e-16 -5.773160e-15
[2,] 1.154632e-14  1.000000e+00 8.881784e-16  7.993606e-15
[3,] 7.993606e-15 -4.551914e-15 1.000000e+00  6.661338e-16
[4,] 6.328271e-15 -2.775558e-16 6.106227e-15  1.000000e+00

In [11]:
ide.P(matrix(rnorm(16),4))

[,1]          [,2]          [,3]          [,4]         
[1,]  1.000000e+00 -5.273559e-16 -8.465451e-16  1.387779e-17
[2,] -3.547510e-16  1.000000e+00  8.153200e-17  2.099015e-16
[3,] -4.128642e-16  2.914335e-16  1.000000e+00 -6.106227e-16
[4,] -2.220446e-16  3.330669e-16  1.110223e-16  1.000000e+00

In [12]:
ide.P(matrix(rnorm(16),4))

[,1]         [,2]          [,3]         [,4]         
[1,] 1.000000e+00 -1.314920e-15 9.298118e-16  1.569925e-16
[2,] 1.887379e-15  1.000000e+00 1.110223e-16 -2.636780e-16
[3,] 2.220446e-16  1.110223e-15 1.000000e+00  3.885781e-16
[4,] 1.332268e-15 -2.886580e-15 6.661338e-16  1.000000e+00

In [13]:
x <- rnorm(100)
y <- x + rnorm(100)
z <- x + 2*y + rnorm(100)


In [22]:
m <- matrix(c(x,y,z),100)
head(m)

[,1]       [,2]       [,3]      
[1,]  0.9988160  0.4172794  2.4607693
[2,]  0.2878284 -0.9167871 -2.0861623
[3,] -1.4318270 -0.2235502 -0.2329351
[4,] -0.4301869  0.5739932  1.1880477
[5,] -0.6812575  0.1829190 -2.0166499
[6,]  0.7153226  1.6973055  4.8651433

In [23]:
head(x)

[1]  0.9988160  0.2878284 -1.4318270 -0.4301869 -0.6812575  0.7153226

In [24]:
cov(m)

[,1]      [,2]      [,3]     
[1,] 1.0486795 0.9504855  2.995186
[2,] 0.9504855 1.9369482  4.696738
[3,] 2.9951862 4.6967380 13.164079

In [25]:
eigen(cov(m))

$values
[1] 15.5496293  0.4436928  0.1563845

$vectors
           [,1]         [,2]       [,3]
[1,] -0.2116304  0.840303736 -0.4991014
[2,] -0.3319436 -0.542110995 -0.7719645
[3,] -0.9192530  0.002302377  0.3936606

In [27]:
m2 <- eigen(cov(m))$vectors
m2

[,1]       [,2]         [,3]      
[1,] -0.2116304  0.840303736 -0.4991014
[2,] -0.3319436 -0.542110995 -0.7719645
[3,] -0.9192530  0.002302377  0.3936606

In [28]:
m2 %*% t(m2)

[,1]          [,2]         [,3]         
[1,]  1.000000e+00 5.551115e-17 -8.326673e-17
[2,]  5.551115e-17 1.000000e+00  2.775558e-16
[3,] -8.326673e-17 2.775558e-16  1.000000e+00

In [29]:
m2 %*% diag(c(1,1,1)) %*% t(m2)

[,1]          [,2]         [,3]         
[1,]  1.000000e+00 5.551115e-17 -8.326673e-17
[2,]  5.551115e-17 1.000000e+00  2.775558e-16
[3,] -8.326673e-17 2.775558e-16  1.000000e+00

In [33]:
m3 <- matrix(c(1/2,1/2,1/2,1/2),2)
m3

[,1] [,2]
[1,] 0.5  0.5 
[2,] 0.5  0.5

In [34]:
m3 %*% m3

[,1] [,2]
[1,] 0.5  0.5 
[2,] 0.5  0.5

In [37]:
m4 <- matrix(c(1/3,sqrt(2/9),sqrt(2/9),2/3),2)
m4

[,1]      [,2]     
[1,] 0.3333333 0.4714045
[2,] 0.4714045 0.6666667

In [38]:
m4 %*% m4

[,1]      [,2]     
[1,] 0.3333333 0.4714045
[2,] 0.4714045 0.6666667

In [39]:
library(ggplot2)

Warning message:
"package 'ggplot2' was built under R version 3.3.2"

In [43]:
prod(2,3)

[1] 6

In [44]:
?mesh

In [45]:
expand.grid(c(1,2,3),c(10,20,30))

Var1 Var2
1 1    10  
2 2    10  
3 3    10  
4 1    20  
5 2    20  
6 3    20  
7 1    30  
8 2    30  
9 3    30